"""icon_name in category aaded

Revision ID: 139516e77d6e
Revises: d08a6ec2cd62
Create Date: 2024-07-17 17:19:57.390420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139516e77d6e'
down_revision: Union[str, None] = 'd08a6ec2cd62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('icon_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'icon_name')
    # ### end Alembic commands ###
