"""trying to fix relationships

Revision ID: 88c60973c410
Revises: 0d94a7ff6e09
Create Date: 2024-07-17 15:41:42.952660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c60973c410'
down_revision: Union[str, None] = '0d94a7ff6e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_program_item_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'program_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('program_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_program_item_id_fkey', 'order', 'program_item', ['program_item_id'], ['id'])
    # ### end Alembic commands ###
