"""init

Revision ID: e340befb61d8
Revises:
Create Date: 2024-07-05 17:15:11.506986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e340befb61d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_id'), 'blacklist', ['id'], unique=False)
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='accountstatus'), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('contract_type', sa.Enum('CDI', 'CDD', 'CIVP', 'APPRENTI', name='contracttype'), nullable=False),
    sa.Column('cnss_number', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    op.create_table('activation_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Employee_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='token_status'), nullable=False),
    sa.ForeignKeyConstraint(['Employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_account_id'), 'activation_account', ['id'], unique=False)
    op.create_table('change_password',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Employee_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='token_status'), nullable=False),
    sa.ForeignKeyConstraint(['Employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_password_id'), 'change_password', ['id'], unique=False)
    op.create_table('employee_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('SUPER_USER', 'ADMIN', 'VENDOR', 'INVENTORY_MANAGER', name='role'), nullable=True),
    sa.Column('Employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_role_id'), 'employee_role', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_role_id'), table_name='employee_role')
    op.drop_table('employee_role')
    op.drop_index(op.f('ix_change_password_id'), table_name='change_password')
    op.drop_table('change_password')
    op.drop_index(op.f('ix_activation_account_id'), table_name='activation_account')
    op.drop_table('activation_account')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_blacklist_id'), table_name='blacklist')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
